### ISSUE TITLE
[suggestion] - calling youtube-dl and ffmpeg from javascript to accomplish the same result

### ISSUE THREAD

**Issue by ghost** [Creeplays/SongAPI#5]
#### [suggestion] - calling youtube-dl and ffmpeg from javascript to accomplish the same result

<sub>you can add youtube-dl and ffmpeg to the package and run the following shell command line from javascript to get the same result:</sub>

- <sub>```youtube-dl -x --audio-format format URL ```</sub>

**Comment by CertainLach** [comment]
@tem44 This repo is for songsterr.com, not for youtube
