### ISSUE TITLE
Not Working (401 Authorization Required)

### ISSUE THREAD

**Issue by brhndursun** [Creeplays/SongAPI#7]
Currently it is not working and I think it will never work again :(

`main.73dfe997.js:1 GET https://www.songsterr.com/static/js/plus-player-actions.50c71029.js net::ERR_ABORTED 401`

OS: Mac OSX Latest
Browser: Chrome Latest
Extension downloaded from store

**Comment by CertainLach** [comment]
Seems like. I will try to fix by embedding this file into extension soon

**Comment by brhndursun** [comment]
I'd do the same thing but I didn't find the js file on internet...

**Comment by CertainLach** [comment]
Temporary workaround: go to demo song page, then to normal song, and it's working

**Comment by CertainLach** [comment]
File loaded on demo page: https://bin.0la.ch/xotuheqaje.js
Seems like webpack's chunk 373 code is equals to chunk 8 (The missing one when setting hasPlus=true).
There is demo features loader in main.js
![изображение](https://user-images.githubusercontent.com/6235312/55967310-869e9b00-5c93-11e9-9f51-ee0aa12c0241.png)

**Comment by CertainLach** [comment]
Tried to hack around this.
For now, you can use this code in tempermonkey/greasemonkey: #27ba202

**Comment by CertainLach** [comment]
Chrome extension is updated, also updated downloading feature and merged with this.
